package main

import (
	"bytes"
	"encoding/xml"
	"errors"
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strconv"
	"strings"

	"github.com/bojieli/queqiao/internal/profile"
)

// A supervised client is not optional equipment. The process exits when any
// provider's listener stops, so an operator who starts it by hand gets a proxy
// that disappears on the first failure and does not come back. Generating the
// definition here rather than shipping a template is what keeps it truthful:
// the paths come from this machine, and the argument list has one source.

const (
	defaultServiceLabel = "me.01.queqiao.client"
	defaultServiceUnit  = "queqiao-client"
)

var serviceNamePattern = regexp.MustCompile(`^[A-Za-z0-9][A-Za-z0-9._-]*$`)

type serviceConfig struct {
	label         string
	unit          string
	binary        string
	profile       string
	providers     string
	listen        string
	localAddress  string
	metricsListen string
	logLevel      string
	pathProfile   string
}

// arguments returns everything after the binary. The supervisor-specific tail
// is added by each renderer: launchd discards stderr unless a path is
// configured, so the rotating JSON file is the only useful surface there,
// while journald keeps it on Linux.
func (c serviceConfig) arguments() []string {
	args := []string{"client"}
	if c.providers != "" {
		args = append(args, "--providers", c.providers)
	} else {
		args = append(args, "--profile", c.profile, "--listen", c.listen)
	}
	args = append(args, "--local-address", c.localAddress)
	if c.pathProfile != "" {
		args = append(args, "--path-profile", c.pathProfile)
	}
	if c.metricsListen != "" {
		args = append(args, "--metrics-listen", c.metricsListen)
	}
	return append(args,
		"--log-level", c.logLevel,
		"--log-format", "json",
		"--telemetry-log-interval", "5s",
	)
}

func xmlEscape(value string) string {
	var buffer bytes.Buffer
	if err := xml.EscapeText(&buffer, []byte(value)); err != nil {
		// EscapeText only fails when the writer fails, and a bytes.Buffer
		// does not. Returning the raw value would emit malformed XML.
		return ""
	}
	return buffer.String()
}

// systemdQuote produces one double-quoted token. systemd unescapes C-style
// backslash sequences inside such a token, so both metacharacters need one.
func systemdQuote(value string) string {
	replaced := strings.ReplaceAll(value, `\`, `\\`)
	replaced = strings.ReplaceAll(replaced, `"`, `\"`)
	return `"` + replaced + `"`
}

func renderLaunchAgent(c serviceConfig) string {
	var b strings.Builder
	b.WriteString(`<?xml version="1.0" encoding="UTF-8"?>` + "\n")
	b.WriteString("<!-- Generated by `queqiaod service install`. Re-run that command after\n")
	b.WriteString("     changing profiles or ports; edits made here are overwritten. -->\n")
	b.WriteString(`<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">` + "\n")
	b.WriteString(`<plist version="1.0">` + "\n<dict>\n")
	fmt.Fprintf(&b, "  <key>Label</key>\n  <string>%s</string>\n\n", xmlEscape(c.label))
	b.WriteString("  <key>ProgramArguments</key>\n  <array>\n")
	fmt.Fprintf(&b, "    <string>%s</string>\n", xmlEscape(c.binary))
	for _, argument := range append(c.arguments(), "--log-stderr=false") {
		fmt.Fprintf(&b, "    <string>%s</string>\n", xmlEscape(argument))
	}
	b.WriteString("  </array>\n\n")
	b.WriteString("  <key>RunAtLoad</key>\n  <true/>\n\n")
	b.WriteString("  <key>KeepAlive</key>\n  <dict>\n    <key>SuccessfulExit</key>\n    <false/>\n  </dict>\n\n")
	b.WriteString("  <key>ProcessType</key>\n  <string>Interactive</string>\n")
	b.WriteString("</dict>\n</plist>\n")
	return b.String()
}

func renderSystemdUnit(c serviceConfig) string {
	execStart := systemdQuote(c.binary)
	for _, argument := range c.arguments() {
		execStart += " " + systemdQuote(argument)
	}
	var b strings.Builder
	b.WriteString("# Generated by `queqiaod service install`. Re-run that command after\n")
	b.WriteString("# changing profiles or ports; edits made here are overwritten.\n")
	b.WriteString("[Unit]\n")
	b.WriteString("Description=queqiao local SOCKS5 client\n")
	b.WriteString("Documentation=https://github.com/bojieli/queqiao\n")
	b.WriteString("After=network-online.target\n")
	b.WriteString("Wants=network-online.target\n\n")
	b.WriteString("[Service]\n")
	b.WriteString("Type=simple\n")
	fmt.Fprintf(&b, "ExecStart=%s\n", execStart)
	b.WriteString("# The process exits when any provider's listener stops, so a partially\n")
	b.WriteString("# working client never looks healthy. Restarting is what makes that safe.\n")
	b.WriteString("Restart=on-failure\n")
	b.WriteString("RestartSec=2s\n")
	b.WriteString("NoNewPrivileges=true\n")
	b.WriteString("PrivateTmp=true\n")
	b.WriteString("LockPersonality=true\n")
	b.WriteString("RestrictRealtime=true\n")
	// AF_NETLINK is how the client reads this machine's interfaces, which it
	// does to resolve --local-address: `if:NAME` needs the named interface's
	// address, and `auto` needs to know whether the choice is ambiguous.
	// Without it the unit installs, binds its listener, and looks healthy,
	// then fails every flow with "enumerate local interfaces: netlinkrib:
	// address family not supported by protocol" - and the option this breaks
	// is the one the installer recommends when `auto` cannot decide.
	b.WriteString("RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX AF_NETLINK\n")
	b.WriteString("SystemCallArchitectures=native\n")
	b.WriteString("LimitNOFILE=65536\n\n")
	b.WriteString("[Install]\n")
	b.WriteString("WantedBy=default.target\n")
	return b.String()
}

func servicePath(c serviceConfig) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("locate home directory: %w", err)
	}
	switch runtime.GOOS {
	case "darwin":
		return filepath.Join(home, "Library", "LaunchAgents", c.label+".plist"), nil
	case "linux":
		return filepath.Join(home, ".config", "systemd", "user", c.unit+".service"), nil
	default:
		return "", fmt.Errorf("queqiaod service supports macOS and Linux; on %s define the service with the platform's own tooling", runtime.GOOS)
	}
}

func renderService(c serviceConfig) (string, error) {
	switch runtime.GOOS {
	case "darwin":
		return renderLaunchAgent(c), nil
	case "linux":
		return renderSystemdUnit(c), nil
	default:
		return "", fmt.Errorf("queqiaod service supports macOS and Linux, not %s", runtime.GOOS)
	}
}

func runService(args []string) error {
	if len(args) == 0 {
		return errors.New("service command is required: install, uninstall, status, or print")
	}
	switch args[0] {
	case "install":
		return runServiceInstall(args[1:], true)
	case "print":
		return runServiceInstall(args[1:], false)
	case "uninstall":
		return runServiceUninstall(args[1:])
	case "status":
		return runServiceStatus(args[1:])
	default:
		return fmt.Errorf("unknown service command %q; want install, uninstall, status, or print", args[0])
	}
}

func bindServiceFlags(fs *flag.FlagSet, c *serviceConfig) {
	fs.StringVar(&c.profile, "profile", "", "client profile to serve")
	fs.StringVar(&c.providers, "providers", "", "multi-provider manifest to serve")
	fs.StringVar(&c.listen, "listen", "127.0.0.1:12080", "SOCKS5 listen address (only with --profile)")
	fs.StringVar(&c.localAddress, "local-address", "auto", "outer source: auto, IP, or if:NAME")
	fs.StringVar(&c.metricsListen, "metrics-listen", "127.0.0.1:12090", "loopback metrics address, empty to disable")
	fs.StringVar(&c.logLevel, "log-level", "info", "debug, info, warn, or error")
	fs.StringVar(&c.pathProfile, "path-profile", "", "path profile the service runs, empty for the default. See docs/DEPLOYING-DC-PROFILE.md before choosing dc-long-haul")
	fs.StringVar(&c.label, "label", defaultServiceLabel, "macOS LaunchAgent label")
	fs.StringVar(&c.unit, "service-name", defaultServiceUnit, "Linux systemd --user unit name")
	fs.StringVar(&c.binary, "binary", "", "queqiaod path to run (default: this executable)")
}

func (c *serviceConfig) resolve() error {
	if !serviceNamePattern.MatchString(c.label) {
		return fmt.Errorf("invalid --label %q; use letters, digits, dot, underscore, and dash", c.label)
	}
	if !serviceNamePattern.MatchString(c.unit) {
		return fmt.Errorf("invalid --service-name %q; use letters, digits, dot, underscore, and dash", c.unit)
	}
	// Resolved here rather than at first start, so a misspelled profile is a
	// failed install instead of a service that comes up carrying policy the
	// operator did not ask for.
	if c.pathProfile != "" {
		if _, err := profile.ByName(c.pathProfile); err != nil {
			return err
		}
	}
	if c.profile == "" && c.providers == "" {
		return errors.New("--profile or --providers is required; run queqiaod enroll first to create one")
	}
	if c.profile != "" && c.providers != "" {
		return errors.New("--profile and --providers cannot be combined")
	}
	if c.providers != "" && c.listen != "127.0.0.1:12080" {
		return errors.New("--listen cannot be combined with --providers; each provider carries its own listener")
	}
	if c.binary == "" {
		executable, err := os.Executable()
		if err != nil {
			return fmt.Errorf("locate this executable: %w", err)
		}
		// A service definition must survive the shell that wrote it, so the
		// path is resolved through symlinks and made absolute now rather than
		// being left as whatever argv[0] happened to be.
		if resolved, err := filepath.EvalSymlinks(executable); err == nil {
			executable = resolved
		}
		c.binary = executable
	}
	for _, field := range []*string{&c.binary, &c.profile, &c.providers} {
		if *field == "" {
			continue
		}
		absolute, err := filepath.Abs(*field)
		if err != nil {
			return fmt.Errorf("resolve %s: %w", *field, err)
		}
		*field = absolute
	}
	for _, path := range []string{c.profile, c.providers} {
		if path == "" {
			continue
		}
		if _, err := os.Stat(path); err != nil {
			return fmt.Errorf("%s is not readable; enroll first, or correct the path: %w", path, err)
		}
	}
	return nil
}

func runServiceInstall(args []string, install bool) error {
	name := "service print"
	if install {
		name = "service install"
	}
	fs := newFlagSet(name)
	var config serviceConfig
	bindServiceFlags(fs, &config)
	noStart := fs.Bool("no-start", false, "write the definition without loading it")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if err := requireNoArguments(fs); err != nil {
		return err
	}
	if err := config.resolve(); err != nil {
		return err
	}
	definition, err := renderService(config)
	if err != nil {
		return err
	}
	if !install {
		fmt.Print(definition)
		return nil
	}
	path, err := servicePath(config)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return fmt.Errorf("create service directory: %w", err)
	}
	// The definition names the profile path, so it is written owner-only for
	// the same reason the profile is.
	if err := os.WriteFile(path, []byte(definition), 0o600); err != nil {
		return fmt.Errorf("write service definition: %w", err)
	}
	fmt.Printf("Wrote %s\n", path)
	if *noStart {
		fmt.Println("Not loaded (--no-start).")
		return nil
	}
	if err := loadService(config, path); err != nil {
		return err
	}
	fmt.Printf("Loaded %s. It starts automatically from now on.\n", serviceIdentity(config))
	fmt.Printf("Logs: %s logs client\n", config.binary)
	return nil
}

func serviceIdentity(c serviceConfig) string {
	if runtime.GOOS == "darwin" {
		return c.label
	}
	return c.unit + ".service"
}

// runCommand is the single place this program starts another one. Every call
// site passes a literal program name -- launchctl, systemctl, loginctl -- and
// no shell is involved, so an argument cannot become a command. The only
// operator-supplied values that reach an argument are the label and unit name,
// both matched against serviceNamePattern first; the remaining arguments are
// absolute paths this process resolved itself.
//
// Concentrating it here is deliberate: one reviewed line is worth more than
// nine call sites each carrying their own annotation.
func runCommand(name string, args ...string) error {
	return execute(false, name, args...)
}

// runCommandQuiet is for calls whose failure is expected and handled. The
// first install has nothing to boot out, and launchctl reports that on stderr
// as "Boot-out failed: 3: No such process" -- an alarming line for a step that
// worked exactly as intended.
func runCommandQuiet(name string, args ...string) error {
	return execute(true, name, args...)
}

func execute(quiet bool, name string, args ...string) error {
	command := exec.Command(name, args...) // #nosec G204 G702 -- see above.
	if !quiet {
		command.Stdout = os.Stderr
		command.Stderr = os.Stderr
	}
	if err := command.Run(); err != nil {
		return fmt.Errorf("%s %s: %w", name, strings.Join(args, " "), err)
	}
	return nil
}

func loadService(c serviceConfig, path string) error {
	switch runtime.GOOS {
	case "darwin":
		domain := "gui/" + strconv.Itoa(os.Getuid())
		// bootout first: kickstart restarts the definition launchd already
		// cached and would not re-read the arguments just written.
		_ = runCommandQuiet("launchctl", "bootout", domain+"/"+c.label)
		return runCommand("launchctl", "bootstrap", domain, path)
	case "linux":
		if err := runCommand("systemctl", "--user", "daemon-reload"); err != nil {
			return fmt.Errorf("%w\nA systemd --user session is required; log in on the desktop or set XDG_RUNTIME_DIR", err)
		}
		if err := runCommand("systemctl", "--user", "enable", "--now", c.unit); err != nil {
			return err
		}
		// Without lingering the user manager exists only while the account is
		// logged in, so the client would not come back after a reboot.
		if user := os.Getenv("USER"); user != "" {
			if err := runCommandQuiet("loginctl", "enable-linger", user); err != nil {
				fmt.Fprintf(os.Stderr, "NOTE: could not enable lingering (%v).\nRun 'sudo loginctl enable-linger %s' so the client starts at boot without a login.\n", err, user)
			}
		}
		return nil
	default:
		return fmt.Errorf("cannot load a service on %s", runtime.GOOS)
	}
}

func runServiceUninstall(args []string) error {
	fs := newFlagSet("service uninstall")
	var config serviceConfig
	fs.StringVar(&config.label, "label", defaultServiceLabel, "macOS LaunchAgent label")
	fs.StringVar(&config.unit, "service-name", defaultServiceUnit, "Linux systemd --user unit name")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if err := requireNoArguments(fs); err != nil {
		return err
	}
	if !serviceNamePattern.MatchString(config.label) || !serviceNamePattern.MatchString(config.unit) {
		return errors.New("invalid --label or --service-name")
	}
	path, err := servicePath(config)
	if err != nil {
		return err
	}
	switch runtime.GOOS {
	case "darwin":
		_ = runCommandQuiet("launchctl", "bootout", "gui/"+strconv.Itoa(os.Getuid())+"/"+config.label)
	case "linux":
		_ = runCommandQuiet("systemctl", "--user", "disable", "--now", config.unit)
	}
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("remove service definition: %w", err)
	}
	if runtime.GOOS == "linux" {
		_ = runCommandQuiet("systemctl", "--user", "daemon-reload")
	}
	// The profile is deliberately left in place: its invitation is already
	// consumed, so deleting it would destroy a device that cannot be reissued.
	fmt.Printf("Removed %s. Enrolled profiles were left untouched.\n", path)
	return nil
}

func runServiceStatus(args []string) error {
	fs := newFlagSet("service status")
	var config serviceConfig
	fs.StringVar(&config.label, "label", defaultServiceLabel, "macOS LaunchAgent label")
	fs.StringVar(&config.unit, "service-name", defaultServiceUnit, "Linux systemd --user unit name")
	if err := fs.Parse(args); err != nil {
		return err
	}
	if err := requireNoArguments(fs); err != nil {
		return err
	}
	path, err := servicePath(config)
	if err != nil {
		return err
	}
	fmt.Printf("definition: %s\n", path)
	// path comes from servicePath with a pattern-validated name. Reporting on
	// the operator's own service file is the purpose of this command.
	if _, err := os.Stat(path); err != nil {
		fmt.Println("installed:  no")
		fmt.Println("Install it with: queqiaod service install --profile PATH")
		return nil
	}
	fmt.Println("installed:  yes")
	loaded := false
	switch runtime.GOOS {
	case "darwin":
		loaded = runCommandQuiet("launchctl", "print", "gui/"+strconv.Itoa(os.Getuid())+"/"+config.label) == nil
	case "linux":
		loaded = runCommandQuiet("systemctl", "--user", "is-active", config.unit) == nil
	}
	if loaded {
		fmt.Println("loaded:     yes")
	} else {
		fmt.Println("loaded:     no")
		fmt.Println("Load it with: queqiaod service install --profile PATH")
	}
	return nil
}
