package identity

import (
	"bytes"
	"crypto/ed25519"
	"crypto/tls"
	"crypto/x509"
	"encoding/base64"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"net/url"
	"os"
	"strings"
	"time"
)

const (
	InvitationVersion = 1
	ProfileVersion    = 1
	maxInvitationSize = 4096
)

type Invitation struct {
	Version      int    `json:"v"`
	ProviderName string `json:"name"`
	ProviderID   string `json:"provider"`
	Endpoint     string `json:"endpoint"`
	GatewayID    string `json:"gateway"`
	RootPin      string `json:"root"`
	Token        string `json:"token"`
	ExpiresAt    string `json:"expires"`
}

// ClientProfile is generated by enrollment and written mode 0600. The
// private key is represented as PKCS#8 only in this portable fallback format;
// a GUI can replace it with an operating-system keychain reference without
// changing the network identity model.
type ClientProfile struct {
	Version           int    `json:"version"`
	Name              string `json:"name"`
	ProviderID        string `json:"provider_id"`
	Endpoint          string `json:"endpoint"`
	GatewayID         string `json:"gateway_id"`
	RootPin           string `json:"root_pin"`
	RootCertificate   string `json:"root_certificate_pem"`
	AccountID         string `json:"account_id"`
	DeviceID          string `json:"device_id"`
	DeviceName        string `json:"device_name"`
	DeviceCertificate string `json:"device_certificate_pem"`
	DevicePrivateKey  string `json:"device_private_key_pem"`
	CreatedAt         string `json:"created_at"`
	// HopPortCount enables UDP port hopping to evade per-port GFW blocking.
	// 0 and 1 both mean disabled (single port). Values ≥ 2 cause the client
	// to maintain a list of that many ports and hop among them reactively when
	// sustained packet loss is detected on the current port.
	HopPortCount int `json:"hop_port_count,omitempty"`
}

func (p *Provider) CreateInvitation(account string, ttl time.Duration, now time.Time) (string, Invitation, error) {
	if now.IsZero() {
		now = time.Now()
	}
	resolved, ok := p.Store.FindAccount(account)
	if !ok {
		return "", Invitation{}, errors.New("unknown account")
	}
	record, token, err := p.Store.CreateInvite(resolved.ID, ttl, now)
	if err != nil {
		return "", Invitation{}, err
	}
	invitation := Invitation{
		Version: InvitationVersion, ProviderName: p.Metadata.Name,
		ProviderID: p.Metadata.ProviderID, Endpoint: p.Metadata.Endpoint,
		GatewayID: p.Metadata.GatewayID, RootPin: p.Metadata.RootPin,
		Token: token, ExpiresAt: record.ExpiresAt,
	}
	encoded, err := invitation.URI()
	if err != nil {
		return "", Invitation{}, err
	}
	return encoded, invitation, nil
}

func (i Invitation) Validate(now time.Time) error {
	if err := i.validateEnvelope(); err != nil {
		return err
	}
	expires, _ := time.Parse(time.RFC3339, i.ExpiresAt)
	if !nowOrTime(now).Before(expires) {
		return errors.New("invitation has expired")
	}
	if expires.After(nowOrTime(now).Add(7*24*time.Hour + certificateClockSkew)) {
		return errors.New("invitation lifetime exceeds seven days")
	}
	return nil
}

// validateEnvelope authenticates the immutable data needed for an exact
// interrupted-enrollment retry without applying the invitation's original
// use-by time. The provider still enforces expiry for first use and permits a
// consumed-token retry only for the already registered name and public key.
func (i Invitation) validateEnvelope() error {
	if i.Version != InvitationVersion {
		return fmt.Errorf("unsupported invitation version %d", i.Version)
	}
	if i.ProviderName != strings.TrimSpace(i.ProviderName) || i.ProviderName == "" || len(i.ProviderName) > 128 || !validID(i.ProviderID) || !validID(i.GatewayID) || i.RootPin == "" {
		return errors.New("invitation has incomplete provider identity")
	}
	if err := validateEndpoint(i.Endpoint); err != nil {
		return err
	}
	if raw, err := base64.RawURLEncoding.DecodeString(i.RootPin); err != nil || len(raw) != sha256Size {
		return errors.New("invitation has invalid provider root pin")
	}
	if raw, err := base64.RawURLEncoding.DecodeString(i.Token); err != nil || len(raw) != 32 {
		return errors.New("invitation has invalid enrollment token")
	}
	if _, err := time.Parse(time.RFC3339, i.ExpiresAt); err != nil {
		return errors.New("invitation has invalid expiration")
	}
	return nil
}

const sha256Size = 32

func (i Invitation) URI() (string, error) {
	if err := i.Validate(time.Now()); err != nil {
		return "", err
	}
	data, err := json.Marshal(i)
	if err != nil {
		return "", fmt.Errorf("encode invitation: %w", err)
	}
	if len(data) > maxInvitationSize {
		return "", errors.New("invitation is too large")
	}
	return "queqiao://enroll/" + base64.RawURLEncoding.EncodeToString(data), nil
}

func ParseInvitation(text string, now time.Time) (Invitation, error) {
	if len(text) > maxInvitationSize*2 {
		return Invitation{}, errors.New("invitation URI is too large")
	}
	u, err := url.Parse(strings.TrimSpace(text))
	if err != nil || u.Scheme != "queqiao" || u.Host != "enroll" || u.RawQuery != "" || u.Fragment != "" {
		return Invitation{}, errors.New("invalid Queqiao invitation URI")
	}
	raw := strings.TrimPrefix(u.EscapedPath(), "/")
	data, err := base64.RawURLEncoding.DecodeString(raw)
	if err != nil || len(data) == 0 || len(data) > maxInvitationSize {
		return Invitation{}, errors.New("invalid Queqiao invitation payload")
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var invitation Invitation
	if err := decoder.Decode(&invitation); err != nil {
		return Invitation{}, fmt.Errorf("decode invitation: %w", err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		return Invitation{}, errors.New("invitation contains trailing data")
	}
	if err := invitation.Validate(now); err != nil {
		return Invitation{}, err
	}
	return invitation, nil
}

func (p ClientProfile) Save(path string) error {
	unlock, err := lockFile(path + ".lock")
	if err != nil {
		return err
	}
	defer unlock()
	return p.saveUnlocked(path)
}

func (p ClientProfile) saveUnlocked(path string) error {
	if _, err := p.Credentials(); err != nil {
		return err
	}
	data, err := json.MarshalIndent(p, "", "  ")
	if err != nil {
		return fmt.Errorf("encode client profile: %w", err)
	}
	return writeFileAtomic(path, append(data, '\n'), 0o600)
}

// SaveNew installs an enrolled profile without replacing an existing device
// identity. Renewal deliberately uses Save; first enrollment uses SaveNew so
// concurrent imports cannot silently discard a private key.
func (p ClientProfile) SaveNew(path string) error {
	unlock, err := lockFile(path + ".lock")
	if err != nil {
		return err
	}
	defer unlock()
	if _, err := os.Stat(path); err == nil {
		return fmt.Errorf("client profile already exists: %s", path)
	} else if !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("inspect client profile: %w", err)
	}
	return p.saveUnlocked(path)
}

func LoadClientProfile(path string) (ClientProfile, error) {
	info, err := os.Stat(path)
	if err != nil {
		return ClientProfile{}, fmt.Errorf("inspect client profile: %w", err)
	}
	if err := checkPrivatePermissions(info); err != nil {
		return ClientProfile{}, fmt.Errorf("client profile %s: %w", path, err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return ClientProfile{}, fmt.Errorf("read client profile: %w", err)
	}
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	var profile ClientProfile
	if err := decoder.Decode(&profile); err != nil {
		return ClientProfile{}, fmt.Errorf("decode client profile: %w", err)
	}
	var trailing any
	if err := decoder.Decode(&trailing); !errors.Is(err, io.EOF) {
		return ClientProfile{}, errors.New("client profile contains trailing data")
	}
	if _, err := profile.Credentials(); err != nil {
		return ClientProfile{}, err
	}
	return profile, nil
}

func (p ClientProfile) Credentials() (ClientCredentials, error) {
	if p.Version != ProfileVersion {
		return ClientCredentials{}, fmt.Errorf("unsupported client profile version %d", p.Version)
	}
	if !validID(p.ProviderID) || !validID(p.GatewayID) || !validID(p.AccountID) || !validID(p.DeviceID) || p.RootPin == "" {
		return ClientCredentials{}, errors.New("client profile is incomplete")
	}
	if p.Name != strings.TrimSpace(p.Name) || p.Name == "" || len(p.Name) > 128 ||
		p.DeviceName != strings.TrimSpace(p.DeviceName) || p.DeviceName == "" || len(p.DeviceName) > 128 {
		return ClientCredentials{}, errors.New("client profile has invalid provider or device names")
	}
	if _, err := time.Parse(time.RFC3339, p.CreatedAt); err != nil {
		return ClientCredentials{}, errors.New("client profile has an invalid creation time")
	}
	if err := validateEndpoint(p.Endpoint); err != nil {
		return ClientCredentials{}, err
	}
	rootBlock, rest := pem.Decode([]byte(p.RootCertificate))
	if rootBlock == nil || rootBlock.Type != "CERTIFICATE" || len(bytes.TrimSpace(rest)) != 0 {
		return ClientCredentials{}, errors.New("client profile has an invalid provider root")
	}
	root, err := x509.ParseCertificate(rootBlock.Bytes)
	if err != nil {
		return ClientCredentials{}, fmt.Errorf("parse profile root: %w", err)
	}
	cert, err := tlsKeyPair([]byte(p.DeviceCertificate), []byte(p.DevicePrivateKey))
	if err != nil {
		return ClientCredentials{}, err
	}
	credentials := ClientCredentials{
		ProviderID: p.ProviderID, GatewayID: p.GatewayID,
		Certificate: cert, Root: root, RootPin: p.RootPin,
	}
	if err := credentials.Validate(time.Now()); err != nil {
		return ClientCredentials{}, err
	}
	leaf, _ := x509.ParseCertificate(cert.Certificate[0])
	principal, err := PrincipalFromCertificate(leaf)
	if err != nil {
		return ClientCredentials{}, err
	}
	if principal.AccountID != p.AccountID || principal.DeviceID != p.DeviceID {
		return ClientCredentials{}, errors.New("profile metadata does not match device certificate")
	}
	return credentials, nil
}

func tlsKeyPair(certPEM, keyPEM []byte) (certificate tls.Certificate, err error) {
	certificate, err = tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		return tls.Certificate{}, fmt.Errorf("load client key pair: %w", err)
	}
	return certificate, nil
}

func encodeProfilePrivateKey(key ed25519.PrivateKey) string {
	return string(encodePrivateKey(key))
}
